{% set name = "lalapps" %}
{% set version = "9.0.2" %}

# dependency versions
{% set framel_version = "8.39.2" %}
{% set lal_version = "7.2.0" %}
{% set lalframe_version = "2.0.0" %}
{% set lalmetaio_version = "3.0.0" %}
{% set lalsimulation_version = "4.0.0" %}
{% set lalburst_version = "1.6.0" %}
{% set lalinspiral_version = "3.0.0" %}
{% set lalinference_version = "4.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://software.igwn.org/sources/source/lalsuite/{{ name }}-{{ version }}.tar.xz
  sha256: 78ed2ee49be8dfb6829803b506da17b1094261e1f55fd75486e35456c6c73fba

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    - numpy
    - python
  number: 0
  skip: true  # [win]

requirements:
  build:
    - bc
    - {{ compiler('c') }}
    - help2man >=1.37  # [build_platform == target_platform]
    - make  # [unix]
    - pkg-config
    # extras for cross-compiling
    - cross-python_{{ target_platform }}  # [build_platform != target_platform]
    - python                              # [build_platform != target_platform]
  host:
    - cfitsio
    - gsl
    - liblal >={{ lal_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalframe >={{ lalframe_version }}
    - liblalinference >={{ lalinference_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - libframel >={{ framel_version }}
    - python
    # extras needed for help2man (not when cross compiling)
    - h5py  # [build_platform == target_platform]
    - ligo-segments  # [build_platform == target_platform]
    - numpy  # [build_platform == target_platform]
    - pillow  # [build_platform == target_platform]
    - python-lal >={{ lal_version }}  # [build_platform == target_platform]
    - python-lalburst >={{ lalburst_version }}  # [build_platform == target_platform]
    - python-lalinference >={{ lalinference_version }}  # [build_platform == target_platform]
    - python-lalinspiral >={{ lalinspiral_version }}  # [build_platform == target_platform]
    - python-lalframe >={{ lalframe_version }}  # [build_platform == target_platform]
    - python-lalmetaio >={{ lalmetaio_version }}  # [build_platform == target_platform]
    - python-lalsimulation >={{ lalsimulation_version }}  # [build_platform == target_platform]
    - python-ligo-lw >=1.7.0  # [build_platform == target_platform]
  run:
    - cfitsio
    - gsl
    - h5py
    - libframel >={{ framel_version }}
    - liblal >={{ lal_version }}
    - liblalframe >={{ lalframe_version }}
    - liblalinference >={{ lalinference_version }}
    - liblalmetaio >={{ lalmetaio_version }}
    - liblalsimulation >={{ lalsimulation_version }}
    - liblalburst >={{ lalburst_version }}
    - liblalinspiral >={{ lalinspiral_version }}
    - ligo-segments
    - numpy
    - pillow
    - python
    - python-lal >={{ lal_version }}
    - python-lalburst >={{ lalburst_version }}
    - python-lalframe >={{ lalframe_version }}
    - python-lalinference >={{ lalinference_version }}
    - python-lalinspiral >={{ lalinspiral_version }}
    - python-lalmetaio >={{ lalmetaio_version }}
    - python-lalsimulation >={{ lalsimulation_version }}
    - python-ligo-lw >=1.7.0

test:
  imports:
    - lalapps
    - lalapps.cosmicstring
    - lalapps.inspiral
  requires:
    - ldas-tools-framecpp
  commands:
    # set up test data (creates Z-ilwd_test_frame-600000000-1.gwf)
    - framecpp_sample
    # run --help
    - lalapps_binj --help
    - lalapps_blindinj --help
    - lalapps_cafe --help
    - lalapps_calcexpsnr --help
    - lalapps_cbc_stochasticbank --help
    - lalapps_chirplen --m1 1.4 --m2 1.4 --flow 30
    - lalapps_coh_PTF_inspiral --help
    - lalapps_coinj --help
    - lalapps_cosmicstring_pipe --help
    - lalapps_effdist --help
    - lalapps_exc_resp -h
    - lalapps_fr_ninja --help
    - lalapps_frextr test.gwf Z-ilwd_test_frame-600000000-1.gwf Z0:RAMPED_INT_2U_1
    - lalapps_frinfo Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_frjoin --verbose --output test.gwf Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_frread Z-ilwd_test_frame-600000000-1.gwf Z0:RAMPED_INT_2U_1
    - lalapps_frview --help
    - lalapps_gen_timeslides --help
    - lalapps_gwf2xml --help
    - lalapps_inspfrinj --help
    - lalapps_inspinj --f-lower 30 --waveform IMRPhenomD --gps-start-time 1000000000 --gps-end-time 1000000010 --d-distr volume --l-distr random --m-distr log --i-distr gaussian --incl-std 2 --min-distance 100000 --max-distance 120000 --min-mass1 10 --max-mass1 20 --min-mass2 10 --max-mass2 20 --disable-spin --time-step
      2
    - lalapps_make_nr_hdf_catalog --help
    - lalapps_power --help
    - lalapps_power_likelihood_pipe --help
    - lalapps_power_pipe --help
    - lalapps_random_bank 10 20 10
    - lalapps_randombank --minimum-mass 10 --maximum-mass 20 --number-of-templates 10
    - lalapps_run_sqlite --help
    - lalapps_splitbank --verbose --bank-file P1-TMPLTBANK-0-0.xml --number-of-banks 2 --minimal-match 0.9
    - lalapps_string_apply_vetoes --help
    - lalapps_string_calc_likelihood --help
    - lalapps_string_contour_plotter --help
    - lalapps_string_contour_plotter_largeloops --help
    - lalapps_string_cs_gamma --help
    - lalapps_string_cs_gamma_largeloops --help
    - lalapps_string_final --help
    - lalapps_string_meas_likelihood --help
    - lalapps_string_plot_binj --help
    - lalapps_string_plot_likelihood --help
    - lalapps_tmpltbank --help
    - lalapps_version

about:
  home: https://wiki.ligo.org/Computing/LALSuite
  dev_url: https://git.ligo.org/lscsoft/lalsuite/
  doc_url: https://docs.ligo.org/lscsoft/lalsuite/lalapps/
  license: GPL-2.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: LSC Algorithm Library Applications
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
