{% set name = "lalapps" %}
{% set version = "6.25.0" %}
{% set sha256 = "75aa9f3000cb382b791c82b45f08d24c8d24bb1394fff73d81e7f08d1b08589e" %}

{% set lal_version = "6.21.0" %}
{% set lalburst_version = "1.5.3" %}
{% set lalframe_version = "1.5.0" %}
{% set lalinference_version = "1.11.4" %}
{% set lalinspiral_version = "1.10.0" %}
{% set lalmetaio_version = "1.6.0" %}
{% set lalpulsar_version = "1.18.2" %}
{% set lalsimulation_version = "1.10.0" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: "http://software.ligo.org/lscsoft/source/lalsuite/{{ name }}-{{ version }}.tar.xz"
  sha256: "{{ sha256 }}"
  patches:
    # weave tests are fragile and hardware dependent
    - disable-weave-tests.patch
    # python3 compatibility fixes
    - 0001-lalapps-fix-py3-issues-in-lalapps_cbc_sbank.patch
    - 0002-lalapps-fix-py3-issues-in-lalapps_cbc_sbank_pipe.patch
    - 0003-lalapps-fix-py3-issues-in-lalapps_cbc_sbank_sim.patch
    - 0004-lalapps-fix-python3-imports-in-string_final.patch

build:
  error_overdepending: true
  error_overlinking: true
  ignore_run_exports:
    # run_exports parsing for fftw is broken, so we ignore it
    # manually, for now
    - fftw
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
    - help2man
    - make
    - pkg-config
  host:
    - cfitsio
    - fftw * nompi*
    - gsl
    - h5py
    - lal >={{ lal_version }}
    - lalburst >={{ lalburst_version }}
    - lalframe >={{ lalframe_version }}
    - lalinference >={{ lalinference_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalpulsar >={{ lalpulsar_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - libframe
    - ligo-segments
    - numpy
    - pillow
    - python
    - python-lal >={{ lal_version }}
    - python-lalburst >={{ lalburst_version }}
    - python-lalinference >={{ lalinference_version }}
    - python-lalinspiral >={{ lalinspiral_version }}
    - python-lalframe >={{ lalframe_version }}
    - python-lalmetaio >={{ lalmetaio_version }}
    - python-lalpulsar >={{ lalpulsar_version }}
    - python-lalsimulation >={{ lalsimulation_version }}
    - python-ligo-lw <1.6.0
  run:
    - cfitsio
    - fftw
    - gsl
    - h5py
    - lal >={{ lal_version }}
    - lalframe >={{ lalframe_version }}
    - lalmetaio >={{ lalmetaio_version }}
    - lalsimulation >={{ lalsimulation_version }}
    - lalburst >={{ lalburst_version }}
    - lalinspiral >={{ lalinspiral_version }}
    - lalpulsar >={{ lalpulsar_version }}
    - lalinference >={{ lalinference_version }}
    - libframe
    - ligo-segments
    - numpy
    - pillow
    - python
    - python-lal >={{ lal_version }}
    - python-lalburst >={{ lalburst_version }}
    - python-lalframe >={{ lalframe_version }}
    - python-lalinference >={{ lalinference_version }}
    - python-lalinspiral >={{ lalinspiral_version }}
    - python-lalmetaio >={{ lalmetaio_version }}
    - python-lalpulsar >={{ lalpulsar_version }}
    - python-lalsimulation >={{ lalsimulation_version }}
    - python-ligo-lw <1.6.0

test:
  imports:
    - lalapps
    - lalapps.cosmicstring
    - lalapps.git_version
    - lalapps.inspiral
    - lalapps.inspiralutils
    - lalapps.knope_utils
    - lalapps.power
    - lalapps.pulsarhtmlutils
    - lalapps.pulsarpputils
  requires:
    - ldas-tools-framecpp
  commands:
    # set up test data (creates Z-ilwd_test_frame-600000000-1.gwf)
    - framecpp_sample
    # run --help
    - lalapps_binj --help
    - lalapps_binj_pic --help
    - lalapps_binjfind --help
    - lalapps_blindinj --help
    - lalapps_bucluster --help
    - lalapps_bucut --help
    - lalapps_burca --help
    - lalapps_burca_tailor --help
    - lalapps_cache Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_cafe --help
    - lalapps_calcexpsnr --help
    - lalapps_cbc_sbank --help
    - lalapps_cbc_sbank_choose_mchirp_boundaries --help
    - lalapps_cbc_sbank_hdf5_bankcombiner --help
    - lalapps_cbc_sbank_hdf5_choose_mchirp_boundaries --help
    - lalapps_cbc_sbank_pipe --help
    - lalapps_cbc_sbank_sim --help
    - lalapps_cbc_sbank_sim_pipe --help
    - lalapps_cbc_stochasticbank --help
    - lalapps_chirplen --m1 1.4 --m2 1.4 --flow 30
    - lalapps_coh_PTF_inspiral --help
    - lalapps_coh_PTF_spin_checker --help
    - lalapps_coinj --help
    - lalapps_cosmicstring_pipe --help
    - lalapps_create_pulsar_signal_frame --help
    - lalapps_create_solar_system_ephemeris --help
    - lalapps_create_solar_system_ephemeris_python --help
    - TEMPO2="" lalapps_create_time_correction_ephemeris --help
    - lalapps_effdist --help
    - lalapps_exc_resp -h
    - lalapps_fftw_wisdom --help
    - lalapps_fftwf_wisdom --help
    - lalapps_fits_array_copy --help
    - lalapps_fits_array_imarith --help
    - lalapps_fits_array_list --help
    - lalapps_fits_array_stat --help
    - lalapps_fits_copy --help
    - lalapps_fits_header_delval --help
    - lalapps_fits_header_getval --help
    - lalapps_fits_header_list --help
    - lalapps_fits_header_setval --help
    - lalapps_fits_overview --help
    - lalapps_fits_table_calc --help
    - lalapps_fits_table_list --help
    - lalapps_fits_table_merge --help
    - lalapps_fits_table_select --help
    - lalapps_fr_ninja --help
    - lalapps_frextr test.gwf Z-ilwd_test_frame-600000000-1.gwf Z0:RAMPED_INT_2U_1
    - lalapps_frinfo Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_frjoin --verbose --output test.gwf Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_frread Z-ilwd_test_frame-600000000-1.gwf Z0:RAMPED_INT_2U_1
    - lalapps_frview --help
    - lalapps_gen_timeslides --help
    - lalapps_gwf2xml --help
    - lalapps_heterodyne_pulsar --help
    - lalapps_inspawgfile
    - lalapps_inspfrinj --help
    - lalapps_inspinj --f-lower 30 --waveform IMRPhenomD --gps-start-time 1000000000 --gps-end-time 1000000010 --d-distr volume --l-distr random --m-distr log --i-distr gaussian --incl-std 2 --min-distance 100000 --max-distance 120000 --min-mass1 10 --max-mass1 20 --min-mass2 10 --max-mass2 20 --disable-spin --time-step 2
    - lalapps_inspinjfind --help
    - lalapps_knope --help
    - lalapps_knope_collate_results --help
    #- lalapps_knope_result_page --help  <- needs scotchcorner
    - lalapps_make_nr_hdf_catalog --help
    - lalapps_path2cache <<< Z-ilwd_test_frame-600000000-1.gwf
    - lalapps_plot_tisi --help
    - lalapps_power --help
    - lalapps_power_calc_likelihood --help
    - lalapps_power_final --help
    - lalapps_power_likelihood_pipe --help
    - lalapps_power_pipe --help
    - lalapps_power_plot_binj --help
    - lalapps_power_plot_binjtf --help
    - lalapps_power_plot_burca --help
    - lalapps_power_plot_burca2 --help
    - lalapps_power_plot_burst --help
    - lalapps_power_veto --help
    - lalapps_psinject -h
    - lalapps_pulsar_frequency_evolution --help
    - lalapps_pulsar_parameter_estimation --help
    - lalapps_pulsar_parameter_estimation_nested --help
    - lalapps_random_bank 10 20 10
    - lalapps_randombank --minimum-mass 10 --maximum-mass 20 --number-of-templates 10
    - lalapps_run_sqlite --help
    - lalapps_searchsum2cache --help
    - lalapps_splitSFTs --help
    - lalapps_splitbank --verbose --bank-file P1-TMPLTBANK-0-0.xml --number-of-banks 2 --minimal-match 0.9
    - test "$(LALPULSAR_PREFIX=${PREFIX} lalapps_ssbtodetector --gps 1000000000 --ra 0 --dec 0 --telescope JBO)" == "999999506.306100250"
    - lalapps_string_apply_vetoes --help
    - lalapps_string_calc_likelihood --help
    - lalapps_string_contour_plotter --help
    - lalapps_string_contour_plotter_largeloops --help
    - lalapps_string_cs_gamma --help
    - lalapps_string_cs_gamma_largeloops --help
    - lalapps_string_final --help
    - lalapps_string_meas_likelihood --help
    - lalapps_string_plot_binj --help
    - lalapps_string_plot_likelihood --help
    - test "$(lalapps_tconvert --rfc-2822 800000000)" == "Fri, 13 May 2005 06:13:07 +0000"
    - test "$(lalapps_tconvert Fri, 13 May 2005 06:13:07 +0000)" -eq 800000000
    - lalapps_thinca --help
    - lalapps_tmpltbank --help
    - lalapps_version

about:
  home: "https://wiki.ligo.org/Computing/LALSuite"
  dev_url: "https://git.ligo.org/lscsoft/lalsuite/"
  doc_url: "https://docs.ligo.org/lscsoft/lalsuite/lalapps/"
  license: "GPL-3.0-or-later"
  license_family: "GPL"
  license_file: "COPYING"
  summary: "LSC Algorithm Library Applications"
  description: |
    The LSC Algorithm Library Applications for gravitational wave data
    analysis.  This package contains applications that are built on tools
    in the LSC Algorithm Library.

extra:
  recipe-maintainers:
    - duncanmmacleod
    - skymoo
