travis:
  secure:
    BINSTAR_TOKEN: ZgaVvvaigINJfszrDpmyP1w8YjEaNbfAqo1bODMzG4aWUhm/NW5yE4mDVSj3skQLT8HuemoICxGmIGJP7/AzRUmS7ws3gJJYuIyyktRAiJzdOh2kkmjEYdyrH1mn/9Qeqz+2CiEXagMSA8H1yzHyzkc5jScLnotGKHGpGAXMqXzJ0R5PYoyoE/8QpraKx+utABL/dzVWSJeh2+nEEj9CiZbdwVkyVosIHTB6qHRi1D7S11TBQaGixcRzm8scybjqlhDU/BhyjazOElI2pocb07LM5Vgm8Qwk3spO5Gxpa8a16A71mliewO4XCmUbpXIA+OraqKJKr/NKt8dz8/27Nm+7k2YgRIVdS8GWDtaYaM1OpCCzVLfvBy4e6ivHV0RecZdwYNVvcEX1x2A/HKjpae3Ml8Fo1C9fOU4R9ATtvGo8S4P+kgn4rx6Ukq3rLQstEPdyxDmdSZgsFulczDzKjdKhS7DGeMF4dtZbAs5tpi1XAJNAraVe7vhBFh4yeMGCMHFAz3GAPncy37sKe1FnK39IUCDGQsqmrPfW0caNsIR38PZwLhAfqntZYtvQgPzyBrVKX5qUNnDiZH5JqDL46UD0mKLzst6MbBJlTIs7FaRMiOzIFqeVyyZqY9vemQvKNREU3ArtrvUxsSaEUO8j3ven1rPuVfQPNbv+uPmMAlI=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
